### ISSUE TITLE
postgres authdb missing role, userrole rows

### ISSUE THREAD

**Issue by valhuber** [ApiLogicServer/ApiLogicServer-src#40]
As shown below, the authdb creation fails to create the sa role, and assigning it to user admin.  You can fix this as shown below:

<img width="1049" alt="auth db initialization" src="https://github.com/ApiLogicServer/ApiLogicServer-src/assets/5579631/07d16a13-8b29-4971-9af8-bcd4c0a64100">

**Comment by valhuber** [comment]
Fixed in 10.02.04

**Comment by controlade** [comment]
Hello.   I am testing the APILogicServer in a prototype I am developing for my employer.  So far everything went well, and I could prove ALS's value to the CEO.

Nevertheless, I have tried several times to add Security and create the Image, following this procedure:
https://apilogicserver.github.io/Docs/DevOps-Containers-Deploy-Multi/#:~:text=customers%20returns%20data.-,II.%20Add%20Security,-Using%20the%20terminal

The authdb database was not created automatically when running ApiLogicServer add-auth, so I created it manually using the authdb_postgres.sql script.  After running the authdb command again and restarting the server, the AdminUI goes directly to the list of tables instead of showing the login page.

Please guide me on what I could have done wrong, or if there is any output from the terminal/console that could help determine where the issue could be.  Thanks,

**Comment by valhuber** [comment]
Hi!

Thanks for your interest!  Sorry about the glitch…. We will look into it
and get back to you

Are you able to share your project?

Thanks,
Val

510-703-5909  valhuber on skype

**Comment by valhuber** [comment]
Mr. Vasquez...

Hi, I am Val from the dev team.

You are right - the system does not create your authdb database, so it was correct to create it yourself.

To confirm, this is your project (not the sample project), right?  If you can share it, that might be helpful.

In the next week or so, we are about the release v11 which support Keycloak as an identity manager, as an alternative to using a database.  This supports single-signon, social login (GitHub, gmail etc)... but it is a complex environment.  I am not super familiar with it, but other customers like it.

* Is Keycloak of interest?

It's important I know **what version** you are using.  If possible, can you upgrade to a dev release I can supply?  It is near GA, and has passed all tests except for a few UI bugs in the Admin App.  

* **Let me know** and I can prepare a build.

Now, regarding your current issue.  There are 2 Admin Apps you can run:

1. Use http://localhost:5656/ to see your data
2. Use http://localhost:5656/admin/authentication_admin/ to see the admin data

So, perhaps we were not clear about that... can you confirm what happens when you **try both URLs?**

Also, when you run the apps, click  **Configuration**, and let us know what that says.

Finally, I would like to invite you to our slack channel.  That is the easiest way to keep in touch, exchange messages, and screen share to diagnose issues.

* I will require your **email...**

Famous last works (;)), but I believe we should be able to resolve this.

**Comment by controlade** [comment]
Hello Mr. Huber, 

Yes, it is not a sample project.  I have shared the project and more information with you via e-mail.
I am using version ALS v10.04.61

Thanks,
